# Generated by Django 3.1.6 on 2021-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
                ('productImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
